services:
  fns:
    container_name: fns
    build: .
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      SYMFONY_PROJECT_NAME: fns
    command:
      - "sh"
      - "/data/run.sh"
    working_dir: /data
    ports:
      - 8000:8000
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
