services:
  fns:
    container_name: fns
    build: .
    volumes:
      - type: bind
        source: ./
        target: /app
    environment:
      SYMFONY_PROJECT_NAME: fns
      SYMFONY_PROJECT_SKELETON: symfony/skeleton
      ALLOW_EMPTY_PASSWORD: yes
    working_dir: /data
    ports:
      - 8000:8000
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
    depends_on:
      init-node:
        condition: service_completed_successfully
      init-composer:
        condition: service_completed_successfully

  init-node:
    image: node
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command:
      - "sh"
      - "-c"
      - "npm update && npm run build"
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
    depends_on:
      init-git:
        condition: service_completed_successfully

  init-composer:
    image: composer
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command:
      - "sh"
      - "-c"
      - |-
        ls /etc
        ls /php
        cat /etc/php/php.ini
        composer update
        php bin/console doctrine:migrations:generate -n
        php bin/console doctrine:migrations:migrate -n
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
    depends_on:
      init-git:
        condition: service_completed_successfully


  init-git:
    image: bitnami/git
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command:
      - "sh"
      - "-c"
      - "git config --global --add safe.directory /app && git pull"
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
