services:
  fns:
    container_name: fns
    build: .
    volumes:
      - type: bind
        source: ./
        target: /data
    environment:
      TOKEN: ""
    command:
      - "sh"
      - "/data/run.sh"
    working_dir: /data
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '3'
