<?php

namespace App\Form\Type\Auth;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class EmailCodeType extends AbstractType {
  public function buildForm(FormBuilderInterface $builder, array $options) {
    parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
  }

}